-- MySQL Script generated by MySQL Workbench
-- Tue Dec  9 09:27:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema talariav2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema talariav2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `talariav2` DEFAULT CHARACTER SET latin1 ;
USE `talariav2` ;

-- -----------------------------------------------------
-- Table `talariav2`.`etatticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`etatticket` (
  `idEtatTicket` INT(11) NOT NULL AUTO_INCREMENT,
  `libEtatTicket` VARCHAR(45) NOT NULL,
  `refEtatTicket` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idEtatTicket`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`entreprise` (
  `idEntreprise` INT(11) NOT NULL AUTO_INCREMENT,
  `nomEntreprise` VARCHAR(100) NOT NULL,
  `siretEntreprise` VARCHAR(14) NULL DEFAULT NULL,
  `adresseEntrerprise` VARCHAR(150) NOT NULL,
  `cpEntreprise` CHAR(5) NOT NULL,
  `villeEntreprise` VARCHAR(45) NOT NULL,
  `telEntreprise` CHAR(10) NULL DEFAULT NULL,
  `mailEntreprise` VARCHAR(45) NULL DEFAULT NULL,
  `typeEntreprise` ENUM('client', 'prestataire', 'autre') NOT NULL DEFAULT 'client',
  `dataEntreprise` JSON NULL DEFAULT NULL,
  `created_At` DATETIME NOT NULL,
  `update_At` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idEntreprise`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`service` (
  `idService` INT(11) NOT NULL AUTO_INCREMENT,
  `nomService` VARCHAR(45) NOT NULL,
  `descService` VARCHAR(255) NOT NULL,
  `createAt` DATE NOT NULL,
  `isActiv` TINYINT(4) NOT NULL DEFAULT '1',
  `Entreprise` INT(11) NULL DEFAULT NULL,
  `uuidService` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idService`),
  INDEX `fk_service_Entreprise1_idx` (`Entreprise` ASC) VISIBLE,
  CONSTRAINT `fk_service_Entreprise1`
    FOREIGN KEY (`Entreprise`)
    REFERENCES `talariav2`.`entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`typeticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`typeticket` (
  `idTypeTicket` INT(11) NOT NULL AUTO_INCREMENT,
  `libTypeTicket` VARCHAR(45) NOT NULL,
  `descTypeTicket` VARCHAR(125) NULL DEFAULT NULL,
  `refTypeTicket` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idTypeTicket`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`type_user` (
  `idTypeUser` INT(11) NOT NULL AUTO_INCREMENT,
  `libTypeUser` VARCHAR(45) NOT NULL,
  `refTypeUser` CHAR(10) NULL DEFAULT NULL COMMENT 'Reférence pour exportation\\n4 premiers caractères du libelle suivi de valeur aléatoire',
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `refTypeUser` (`refTypeUser` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(45) NOT NULL,
  `prenomUser` VARCHAR(45) NOT NULL,
  `mailUser` VARCHAR(125) NOT NULL,
  `mdpUser` CHAR(64) NOT NULL,
  `validiteMdp` DATE NOT NULL,
  `uuidUser` VARCHAR(45) NOT NULL,
  `dataAgent` JSON NOT NULL,
  `service_idService` INT(11) NULL DEFAULT NULL,
  `typeUser` INT(11) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `mailUser_UNIQUE` (`mailUser` ASC) VISIBLE,
  INDEX `fk_user_service1_idx` (`service_idService` ASC) VISIBLE,
  INDEX `fk_user_type_user1_idx` (`typeUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_service1`
    FOREIGN KEY (`service_idService`)
    REFERENCES `talariav2`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user1`
    FOREIGN KEY (`typeUser`)
    REFERENCES `talariav2`.`type_user` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`ticket` (
  `idTicket` INT(11) NOT NULL AUTO_INCREMENT,
  `uuidTicket` VARCHAR(45) NOT NULL,
  `contentTicket` TEXT NOT NULL,
  `dateTicket` DATE NOT NULL,
  `objetTicket` VARCHAR(25) NOT NULL,
  `prioriteTicket` ENUM('basse', 'normal', 'haute') NOT NULL DEFAULT 'normal',
  `dataticket` JSON NOT NULL,
  `responsable` INT(11) NULL DEFAULT NULL,
  `Auteur` INT(11) NOT NULL,
  `service` INT(11) NOT NULL COMMENT 'service destinataire',
  `typeTicket` INT(11) NOT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_ticket_user2_idx` (`responsable` ASC) VISIBLE,
  INDEX `fk_ticket_user1_idx` (`Auteur` ASC) VISIBLE,
  INDEX `fk_ticket_service1_idx` (`service` ASC) VISIBLE,
  INDEX `fk_ticket_typeticket1_idx` (`typeTicket` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_service1`
    FOREIGN KEY (`service`)
    REFERENCES `talariav2`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_typeticket1`
    FOREIGN KEY (`typeTicket`)
    REFERENCES `talariav2`.`typeticket` (`idTypeTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`Auteur`)
    REFERENCES `talariav2`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user2`
    FOREIGN KEY (`responsable`)
    REFERENCES `talariav2`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `talariav2`.`changeetat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `talariav2`.`changeetat` (
  `EtatTicket` INT(11) NOT NULL,
  `Ticket` INT(11) NOT NULL,
  `dateEtatTicket` DATETIME NOT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`EtatTicket`, `Ticket`, `dateEtatTicket`),
  INDEX `fk_etatTicket_has_ticket_ticket1_idx` (`Ticket` ASC) VISIBLE,
  INDEX `fk_etatTicket_has_ticket_etatTicket1_idx` (`EtatTicket` ASC) VISIBLE,
  CONSTRAINT `fk_etatTicket_has_ticket_etatTicket1`
    FOREIGN KEY (`EtatTicket`)
    REFERENCES `talariav2`.`etatticket` (`idEtatTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etatTicket_has_ticket_ticket1`
    FOREIGN KEY (`Ticket`)
    REFERENCES `talariav2`.`ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
